---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	Query\20Processor(Query Processor)
	Hotel\20Searching\20Agent(Hotel Searching Agent)
	Place\20Finder\20Agent(Place Finder Agent)
	Route\20Decider\20Agent(Route Decider Agent)
	Itinerary\20Generator\20Agent(Itinerary Generator Agent)
	__end__([<p>__end__</p>]):::last
	Hotel\20Searching\20Agent --> Itinerary\20Generator\20Agent;
	Place\20Finder\20Agent --> Itinerary\20Generator\20Agent;
	Query\20Processor --> Hotel\20Searching\20Agent;
	Query\20Processor --> Place\20Finder\20Agent;
	Query\20Processor --> Route\20Decider\20Agent;
	Route\20Decider\20Agent --> Itinerary\20Generator\20Agent;
	__start__ --> Query\20Processor;
	Itinerary\20Generator\20Agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
